import React from 'react';
import {Table,Button}from 'antd';

class HeroTable extends React.Component{
	constructor(props){
		super(props);
		this.state={
			heroList:[
				{
					key:1,
					avatar:'x',
					id:'001',
					name:'test测试'
				}
			],
			columns:[
				{
					title:'头像',
					dataIndex:'avatar',
					key:'avatar',
					fixed:'left',
					align:'center',
				},
				{
					title:'编号',
					dataIndex:'id',
					key:'id',
					fixed:'left',
					align:'center',
				},
				{
					title:'名称',
					dataIndex:'name',
					key:'name',
					fixed:'left',
					align:'center',
				},
				{
					title:'CV',
					dataIndex:'CV',
					key:'CV',
					align:'center',
				},
				{
					title:'画师',
					dataIndex:'painter',
					key:'painter',
					align:'center',
				},
				{
					title:'性别',
					dataIndex:'sex',
					key:'sex',
					align:'center',
				},
				{
					title:'职介',
					dataIndex:'class',
					key:'class',
					align:'center',
				},
				{
					title:'稀有度',
					dataIndex:'rarity',
					key:'rarity',
					align:'center',
				},
				{
					title:'卡组',
					dataIndex:'card',
					key:'card',
					align:'center',
				},
				{
					title:'阵营',
					dataIndex:'camp',
					key:'camp',
					align:'center',
				},
				{
					title:'特性',
					dataIndex:'property',
					key:'property',
					align:'center',
				},
				{
					title:'保有技能',
					dataIndex:'keepSkill',
					key:'keepSkill',
					align:'center',
				},
				{
					title:'基础HP',
					dataIndex:'baseHP',
					key:'baseHP',
					align:'center',
				},
				{
					title:'基础ATK',
					dataIndex:'baseATK',
					key:'baseATK',
					align:'baseATK',
				},
				{
					title:'满破HP',
					dataIndex:'maxBreakHP',
					key:'maxBreakHP',
					align:'maxBreakHP'
				},
				{
					title:'满破ATK',
					dataIndex:'maxBreakATK',
					key:'maxBreakATK',
					align:'center',
				},
				{
					title:'90级HP',
					dataIndex:'maxLevelHP',
					key:'maxLevelHP',
					align:'maxLevelHP',
				},
				{
					title:'90级ATK',
					dataIndex:'maxLevelATK',
					key:'maxLevelATK',
					align:'center',
				},
				{
					title:'100级HP',
					dataIndex:'maxCupHP',
					key:'maxCupHP',
					align:'center'
				},
				{
					title:'100级ATK',
					dataIndex:'maxCupATK',
					key:'maxCupATK',
					align:'center'
				},
				{
					title:'即死率',
					dataIndex:'dieRate',
					key:'dieRate',
					align:'center'
				},
				{
					title:'掉星律',
					dataIndex:'creatStarRate',
					key:'createStarRate',
					align:'center',	
				},
				{
					title:'暴击率',
					dataIndex:'collectStarRate',
					key:'collectStarRate',
					align:'center'
				},
				{
					title:'绿卡NP率',
					dataIndex:'quickNP',
					key:'quickNP',
					align:'center',
				},
				{
					title:'蓝卡NP率',
					dataIndex:'artsNP',
					key:'artsNP',
					align:'center'
				},
				{
					title:'红卡NP率',
					dataIndex:'busterNP',
					key:'busterNP',
					align:'center'
				},
				{
					title:'EXNP率',
					dataIndex:'ExtraNP',
					key:'ExtraNP',
					align:'center',
				},
				{
					title:'宝具NP率',
					dataIndex:'PhantasmNP',
					key:'PhantasmNP',
					align:'center',
				},
				{
					title:'被击NP',
					dataIndex:'hitNP',
					key:'hitNP',
					align:'center',
				},
				{
                    title: '操作',
                    key: 'operation',
                    fixed: 'right',
					width: 180,
					align:'center',
                    render: () => <span><Button size="small" type="primary">编辑</Button>&nbsp;&nbsp;&nbsp;<Button size="small" type="danger">删除</Button></span>,
                },
			]
		}
	}
	render(){
		return(
			<div>
				<div className="TableMenu">
					<Button type="primary">增加</Button>
				</div>
				<Table columns={this.state.columns} dataSource={this.state.heroList} ></Table>
			</div>
		);
	}
}
export default HeroTable;