import React from 'react';
import {Table,Button}from 'antd';
import HeroPanel from './HeroPanel.js'

class HeroTable extends React.Component{
	constructor(props){
		super(props);
		this.state={
			heroList:[
				{
					key:1,
					avatar:'x',
					id:'001',
					name:'test测试',
					cv:'test测试',
					painter:'test测试',
					area:'test测试',
					source:'test测试',
					sex:'test测试',
					height:'test测试',
					weight:'test测试',
					class:'test测试',
					rarity:'test测试',
					card:'卡组',
					camp:'test测试',
					property:'test测试',
					characteristic:'test测试',
					keepSkill:'test测试',
					baseHP:'test测试',
					baseATK:'test测试',
					maxBreakHP:'test测试',
					maxBreakATK:'test测试',
					maxLevelHP:'test测试',
					maxLevelATK:'test测试',
					maxCupHP:'test测试',
					maxCupATK:'test测试',
					dieRate:'test测试',
					createStarRate:'test测试',
					critWeight:'test测试',
					busterHIT:'test测试',
					quickHIT:'test测试',
					artsHIT:'test测试',
					extraHIT:'test测试',
					busterNP:'test测试',
					quickNP:'test测试',
					artsNP:'test测试',
					extraNP:'test测试',
					hoguNP:'test测试',
					hitNP:'test测试',
					skill1:'test测试',
					skill2:'test测试',
					skill3:'test测试',
					hogu:'test测试',
				}
			],
			columns:[
				{
					title:'头像',
					dataIndex:'avatar',
					key:'avatar',
					fixed:'left',
					align:'center',
				},
				{
					title:'编号',
					dataIndex:'id',
					key:'id',
					fixed:'left',
					align:'center',
				},
				{
					title:'姓名',
					dataIndex:'name',
					key:'name',
					fixed:'left',
					align:'center',
				},
				{
					title:'CV',
					dataIndex:'cv',
					key:'cv',
					align:'center',
				},
				{
					title:'画师',
					dataIndex:'painter',
					key:'painter',
					align:'center',
				},
				{
					title:'地域',
					dataIndex:'area',
					key:'area',
					align:'center'
				},
				{
					title:'出处',
					dataIndex:'source',
					key:'source',
					align:'center'
				},
				{
					title:'性别',
					dataIndex:'sex',
					key:'sex',
					align:'center',
				},
				{
					title:'身高',
					dataIndex:'height',
					key:'height',
					align:'center'
				},
				{
					title:'体重',
					dataIndex:'weight',
					key:'weight',
					align:'center'
				},
				{
					title:'职介',
					dataIndex:'class',
					key:'class',
					align:'center',
				},
				{
					title:'稀有度',
					dataIndex:'rarity',
					key:'rarity',
					align:'center',
				},
				{
					title:'卡组',
					dataIndex:'card',
					key:'card',
					align:'center',
				},
				{
					title:'阵营(天地人星)',
					dataIndex:'camp',
					key:'camp',
					align:'center',
				},
				{
					title:'属性(DND九宫格)',
					dataIndex:'property',
					key:'property',
					align:'center'
				},
				{
					title:'特性',
					dataIndex:'characteristic',
					key:'characteristic',
					align:'center',
				},
				
				{
					title:'保有技能',
					dataIndex:'keepSkill',
					key:'keepSkill',
					align:'center',
				},
				{
					title:'基础HP',
					dataIndex:'baseHP',
					key:'baseHP',
					align:'center',
				},
				{
					title:'基础ATK',
					dataIndex:'baseATK',
					key:'baseATK',
					align:'center',
				},
				{
					title:'满破HP',
					dataIndex:'maxBreakHP',
					key:'maxBreakHP',
					align:'center'
				},
				{
					title:'满破ATK',
					dataIndex:'maxBreakATK',
					key:'maxBreakATK',
					align:'center',
				},
				{
					title:'90级HP',
					dataIndex:'maxLevelHP',
					key:'maxLevelHP',
					align:'center',
				},
				{
					title:'90级ATK',
					dataIndex:'maxLevelATK',
					key:'maxLevelATK',
					align:'center',
				},
				{
					title:'100级HP',
					dataIndex:'maxCupHP',
					key:'maxCupHP',
					align:'center'
				},
				{
					title:'100级ATK',
					dataIndex:'maxCupATK',
					key:'maxCupATK',
					align:'center'
				},
				{
					title:'即死率',
					dataIndex:'dieRate',
					key:'dieRate',
					align:'center'
				},
				{
					title:'掉星律',
					dataIndex:'createStarRate',
					key:'createStarRate',
					align:'center',	
				},
				{
					title:'暴击权重',
					dataIndex:'critWeight',
					key:'critWeight',
					align:'center'
				},
				{
					title:'红卡HIT',
					dataIndex:'busterHIT',
					key:'busterHIT',
					align:'center'	
				},
				{
					title:'绿卡HIT',
					dataIndex:'quickHIT',
					key:'quickHIT',
					align:'center'	
				},
				{
					title:'蓝卡HIT',
					dataIndex:'artsHIT',
					key:'artsHIT',
					align:'center'	
				},
				{
					title:'EXHIT',
					dataIndex:'extraHIT',
					key:'extraHIT',
					align:'center'	
				},
				{
					title:'红卡NP率',
					dataIndex:'busterNP',
					key:'busterNP',
					align:'center'
				},
				{
					title:'绿卡NP率',
					dataIndex:'quickNP',
					key:'quickNP',
					align:'center',
				},
				{
					title:'蓝卡NP率',
					dataIndex:'artsNP',
					key:'artsNP',
					align:'center'
				},
				{
					title:'EXNP率',
					dataIndex:'extraNP',
					key:'extraNP',
					align:'center',
				},
				{
					title:'宝具NP率',
					dataIndex:'hoguNP',
					key:'hoguNP',
					align:'center',
				},
				{
					title:'被击NP',
					dataIndex:'hitNP',
					key:'hitNP',
					align:'center',
				},
				{
					title:'技能1',
					dataIndex:'skill1',
					key:'skill1',
					align:'center'
				},
				{
					title:'技能2',
					dataIndex:'skill2',
					key:'skill2',
					align:'center'
				},
				{
					title:'技能3',
					dataIndex:'skill3',
					key:'skill3',
					align:'center'
				},
				{
					title:'宝具',
					dataIndex:'hogu',
					key:'hogu',
					align:'center'
				},
				{
                    title: '操作',
                    key: 'operation',
                    fixed: 'right',
					width: 180,
					align:'center',
                    render: () => <span><Button size="small" type="primary">编辑</Button>&nbsp;&nbsp;&nbsp;<Button size="small" type="danger">删除</Button></span>,
                },
			],
			panelVisible:false,
		}
	}
	handleAdd=()=>{
        this.setState({
            panelVisible:true
        })
    }
    panelCancel(){
        // console.log(this)
        this.setState({
            panelVisible:false
        })
    }
	render(){
		return(
			<div>
				<div className="TableMenu">
					<Button type="primary" onClick={this.handleAdd}>增加</Button>
				</div>
				<Table columns={this.state.columns} dataSource={this.state.heroList} scroll={{ x: true}}></Table>
				<HeroPanel visible={this.state.panelVisible} handleCancel={()=>this.panelCancel()}></HeroPanel>
			</div>
		);
	}
}
export default HeroTable;